local_backend: true
backend:
  name: git-gateway
  # name: test-repo
  branch: master
publish_mode: editorial_workflow
media_folder: 'public/images'
public_folder: '/images'
logo_url: https://coro.nuovo.website/logoPiccolo.png
collections:
  - label: 'Global'
    name: 'global'
    files:
      - label: 'Settaggi di base'
        name: 'settings'
        file: '_data/settings.json'
        delete: false
        create: true
        fields:
          - { label: 'Titolo', name: 'title', widget: 'string' }
          - { label: 'Sottotitolo', name: 'subtitle', widget: 'string' }
  - label: 'Home'
    name: 'home'
    files:
      - label: 'Pagina iniziale'
        name: 'homepage'
        delete: false
        create: true
        file: '_data/home.json'
        fields:
          - { label: 'Intro', name: 'intro', widget: 'markdown' }
          - {
              label: 'Foto',
              name: 'picture',
              widget: 'image',
              allow_multiple: false,
            }
          - { label: 'Promo', name: 'promo', widget: 'markdown' }

  - label: 'Coristi'
    name: 'coristi'
    label_singular: 'Corista'
    title: 'nome'
    slug: '{{year}}-{{month}}-{{day}}_{{slug}}'
    folder: '_data/coristi'
    extension: json
    create: true
    fields:
      - { label: 'Nominativo', name: 'title', widget: 'string' }
      - {
          label: 'Foto',
          name: 'picture',
          widget: 'image',
          allow_multiple: false,
        }
      - {
          label: 'Voce',
          name: 'voce',
          widget: 'select',
          options: ['Soprano', 'Contralto', 'Tenore', 'Basso'],
        }

  # - name: 'standalone pages'
  #   label: 'Standalone Pages'
  #   folder: 'standalone-pages'
  #   slug: ''
  #   file: 'standalone-pages/.mdx'
  #   create: true
  #   extension: mdx
  #   format: frontmatter
  #   fields:
  #     - { label: 'Title', name: 'title', widget: 'string' }
  #     - {
  #         label: 'SEO Meta Title',
  #         name: 'metaTitle',
  #         widget: 'string',
  #         required: false,
  #       }
  #     - {
  #         label: 'SEO Meta Description',
  #         name: 'metaDesc',
  #         widget: 'string',
  #         required: false,
  #       }
  #     - {
  #         label: 'Social Image',
  #         name: 'socialImage',
  #         widget: 'image',
  #         required: false,
  #       }
  #     - { label: 'Body', name: 'body', widget: 'markdown' }
