local_backend: true
backend:
  name: git-gateway
  # name: test-repo
  branch: master
publish_mode: editorial_workflow
media_folder: 'public/images'
public_folder: '/images'
locale: 'it'
logo_url: https://coro.nuovo.website/logoPiccolo.png
collections:
  - label: 'Global'
    name: 'global'
    files:
      - label: 'Settaggi di base'
        name: 'settings'
        file: '_data/settings.json'
        fields:
          - { label: 'Titolo', name: 'title', widget: 'string' }
          - { label: 'Sottotitolo', name: 'subtitle', widget: 'string' }

      - label: 'Pagina iniziale'
        name: 'homepage'
        file: '_data/home.json'
        fields:
          - { label: 'Intro', name: 'intro', widget: 'markdown' }
          - {
              label: 'Foto',
              name: 'picture',
              widget: 'image',
              allow_multiple: false,
            }
          - { label: 'Promo', name: 'promo', widget: 'markdown' }

      - label: 'In evidenza'
        name: 'in_evidenza'
        title: 'titolo'
        file: '_data/in_evidenza.json'
        fields:
          - { label: 'Titolo breve', name: 'short_title', widget: 'string' }
          - {
              label: 'Descrizione breve',
              name: 'short_description',
              required: false,
              widget: 'markdown',
            }
          - { label: 'Data', name: 'date', widget: 'date' }
          - {
              label: 'Intestazione pagina',
              name: 'headings',
              widget: 'markdown',
            }
          - {
              label: 'Descrizione',
              name: 'description',
              widget: 'markdown',
              required: false,
            }
          - {
              label: 'Foto',
              name: 'picture',
              widget: 'image',
              allow_multiple: true,
              required: false,
            }
          - {
              label: 'Allegati',
              name: 'allegati',
              widget: 'list',
              label_singular: 'allegato',
              allow_multiple: true,
              choose_url: false,
              fields:
                [
                  { label: 'Titolo', name: 'title', widget: 'string' },
                  {
                    label: 'Lingua',
                    name: 'lang',
                    widget: 'select',
                    default: 'it',
                    options:
                      [
                        { label: 'Italiano', value: 'it' },
                        { label: 'Inglese', value: 'en' },
                      ],
                  },
                  {
                    label: 'File',
                    name: 'fileUrl',
                    widget: 'file',
                    media_folder: '/public/docs',
                    public_folder: '/docs',
                  },
                ],
            }
          - {
              label: 'Link esterni',
              name: 'links',
              widget: 'list',
              label_singular: 'Link esterno',
              fields:
                [
                  { label: 'Titolo', name: 'title', widget: 'string' },
                  {
                    label: 'Lingua',
                    name: 'lang',
                    widget: 'select',
                    default: 'it',
                    options:
                      [
                        { label: 'Italiano', value: 'it' },
                        { label: 'Inglese', value: 'en' },
                        { label: 'Tedesco', value: 'de' },
                        { label: 'Spagnolo', value: 'es' },
                      ],
                  },
                  { label: 'Link', name: 'linkUrl', widget: 'string' },
                ],
            }

  - label: 'Coristi'
    name: 'coristi'
    label_singular: 'Corista'
    title: 'nome'
    slug: '{{year}}-{{month}}-{{day}}_{{slug}}'
    folder: '_data/coristi'
    extension: json
    create: true
    fields:
      - { label: 'Nominativo', name: 'title', widget: 'string' }
      - {
          label: 'Foto',
          name: 'picture',
          widget: 'image',
          allow_multiple: false,
        }
      - {
          label: 'Voce',
          name: 'voce',
          widget: 'select',
          options: ['Soprano', 'Contralto', 'Tenore', 'Basso'],
        }

  - label: 'Eventi'
    name: 'eventi'
    label_singular: 'Evento'
    folder: '_data/eventi'
    extension: json
    create: true
    fields:
      - { label: 'Titolo', name: 'title', widget: 'string' }
      - { label: 'Data', name: 'date', widget: 'date' }
      - { label: 'Descrizione', name: 'description', widget: 'markdown' }
      - { label: 'Luogo', name: 'place', widget: 'string', required: false }

  - label: 'Ricordi fotografici'
    name: 'ricordi'
    label_singular: 'Ricordo fotografico'
    folder: '_data/ricordi'
    extension: json
    create: true
    fields: 
      [
        - { label: 'Titolo', name: 'title', widget: 'string' }
        - {
            label: 'Descrizione',
            name: 'description',
            widget: 'markdown',
            required: false,
          }
        - { label: 'Data', name: 'date', widget: 'date', required: false }
        - {
            label: 'Foto',
            name: 'foto',          
            widget: 'list',
            media_folder: '/public/pictures/{{title}}',
            public_folder: '/pictures/{{title}}',
            media_library: { config: { multiple: true } },
          }
      ]
