local_backend: true
backend:
  name: git-gateway
  # name: test-repo
  branch: master
publish_mode: editorial_workflow
media_folder: 'public/images'
public_folder: '/images'
logo_url: https://coro.nuovo.website/logoPiccolo.png
collections:
  - label: 'Global'
    name: 'global'
    files:
      - label: 'Settaggi di base'
        name: 'settings'
        file: '_data/settings.json'
        delete: false
        create: true
        fields:
          - { label: 'Titolo', name: 'title', widget: 'string' }
          - { label: 'Sottotitolo', name: 'subtitle', widget: 'string' }
  - label: 'Home'
    name: 'home'
    files:
      - label: 'Pagina iniziale'
        name: 'homepage'
        delete: false
        create: true
        file: '_data/home.json'
        fields:
          - { label: 'Intro', name: 'intro', widget: 'markdown' }
          - {
              label: 'Foto',
              name: 'picture',
              widget: 'image',
              allow_multiple: false,
            }
          - { label: 'Promo', name: 'promo', widget: 'markdown' }

  - label: 'Coristi'
    name: 'coristi'
    label_singular: 'Corista'
    title: 'nome'
    slug: '{{year}}-{{month}}-{{day}}_{{slug}}'
    folder: '_data/coristi'
    extension: json
    create: true
    fields:
      - { label: 'Nominativo', name: 'title', widget: 'string' }
      - {
          label: 'Foto',
          name: 'picture',
          widget: 'image',
          allow_multiple: false,
        }
      - {
          label: 'Voce',
          name: 'voce',
          widget: 'select',
          options: ['Soprano', 'Contralto', 'Tenore', 'Basso'],
        }

  - label: 'Eventi'
    name: 'eventi'
    label_singular: 'Evento'
    title: 'titolo'
    folder: '_data/eventi'
    extension: json
    create: true
    fields:
      - { label: 'Titolo', name: 'title', widget: 'string' }
      - { label: 'Data', name: 'date', widget: 'date' }
      - { label: 'Descrizione', name: 'description', widget: 'markdown' }
      - { label: 'Luogo', name: 'place', widget: 'string' }

  - label: 'In evidenza'
    name: 'in_evidenza'
    label_singular: 'sezione'
    title: 'titolo'
    folder: '_data/in_evidenza'
    extension: json
    create: true
    fields:
      - { label: 'Titolo breve', name: 'short_title', widget: 'string' }
      - { label: 'Data', name: 'date', widget: 'date' }
      - { label: 'Intestazione pagina', name: 'headings', widget: 'markdown' }
      - {
          label: 'Descrizione',
          name: 'description',
          widget: 'markdown',
          required: false,
        }
      - {
          label: 'Foto',
          name: 'picture',
          widget: 'image',
          allow_multiple: true,
        }
      - {
          label: 'Allegati',
          name: 'allegati',
          widget: 'list',
          label_singular: 'allegato',
          allow_multiple: true,
          fields:
            [
              { label: 'Titolo', name: 'title', widget: 'string' },
              { label: 'File', name: 'file', widget: 'file', required: false },
              {
                label: 'Link',
                name: 'link',
                widget: 'string',
                required: false,
              },
            ],
        }
